# 14 — Final Poster Analysis & Results Integration

## CHRD-Bench: Cross-Lingual Cultural Representation in Text-to-Image Models

Bu notebook, CHRD-Bench çalışmasının önceki notebook'larda elde edilen
sonuçlarını yeniden üretmek yerine, mevcut sonuçları bir araya getirerek
poster sunumunda kullanılacak nihai analiz, tablo ve grafiklerin hazırlanması
amacıyla oluşturulmuştur.

> **Önemli:** Bu notebook veri setini veya görselleri sıfırdan oluşturmaz.
> Önceki notebook'larda üretilmiş ve doğrulanmış sonuçları kullanır.

---

In [17]:
# ============================================================
# 14 — FINAL POSTER ANALYSIS
# CELL 1 — PROJE VE SONUÇ YOLLARI
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Proje kökü
# ------------------------------------------------------------

PROJECT_ROOT = Path("..").resolve()

# ------------------------------------------------------------
# Önceki notebook sonuçları
# ------------------------------------------------------------

RESULTS_DIR = PROJECT_ROOT / "results"

# ------------------------------------------------------------
# Poster çıktılarının tutulacağı klasör
# ------------------------------------------------------------

POSTER_OUTPUT_DIR = RESULTS_DIR / "poster_final"

POSTER_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("=" * 70)
print("14 — FINAL POSTER ANALYSIS")
print("=" * 70)

print("\nProje kökü:")
print(PROJECT_ROOT)

print("\n08 sonuç klasörü:")
print(RESULTS_DIR)

print("\n14 final poster klasörü:")
print(POSTER_OUTPUT_DIR)

print("\n08 sonuç klasörü mevcut:", RESULTS_DIR.exists())

if not RESULTS_DIR.exists():
    raise FileNotFoundError(
        f"\n❌ Results klasörü bulunamadı:\n{RESULTS_DIR}\n\n"
        "14 notebook'un proje içindeki konumunu kontrol et."
    )

print("\n✅ CELL 1 tamamlandı.")

======================================================================
14 — FINAL POSTER ANALYSIS
======================================================================

Proje kökü:
C:\CHRD_Project

08 sonuç klasörü:
C:\CHRD_Project\results

14 final poster klasörü:
C:\CHRD_Project\results\poster_final

08 sonuç klasörü mevcut: True

✅ CELL 1 tamamlandı.

In [18]:
# ============================================================
# CELL 2 — 08 POSTER ÇIKTILARINI KONTROL ET
# ============================================================

print("=" * 70)
print("CELL 2 — ÖNCEKİ POSTER ÇIKTILARI")
print("=" * 70)

result_files = sorted(
    [
        f for f in RESULTS_DIR.rglob("*")
        if f.is_file()
    ]
)

print("\n08 tarafından oluşturulmuş dosyalar:\n")

if not result_files:
    print("⚠️ Results klasörü boş.")
else:

    for file_path in result_files:

        relative_path = file_path.relative_to(
            RESULTS_DIR
        )

        size_kb = file_path.stat().st_size / 1024

        print(
            f"{relative_path} "
            f"| {size_kb:.1f} KB"
        )


print("\nToplam sonuç dosyası:", len(result_files))

print("\n✅ CELL 2 tamamlandı.")

======================================================================
CELL 2 — ÖNCEKİ POSTER ÇIKTILARI
======================================================================

08 tarafından oluşturulmuş dosyalar:

chrd_similarity_results.csv | 6.4 KB
cultural_value_bar.png | 62.7 KB
dataset_summary.csv | 0.1 KB
improved_similarity.csv | 0.1 KB
location_bar.png | 144.3 KB
motif1_bar.png | 149.4 KB
motif2_bar.png | 144.9 KB
motif_pairs.png | 208.2 KB
prompt_statistics.csv | 0.1 KB
prompt_summary.csv | 0.1 KB
real_image_similarity.csv | 6.7 KB
similarity_results.csv | 0.1 KB
theme_bar.png | 113.7 KB
theme_horizontal.png | 74.2 KB
theme_location_heatmap.png | 171.0 KB
theme_pie.png | 158.8 KB
top_locations.png | 118.3 KB

Toplam sonuç dosyası: 17

✅ CELL 2 tamamlandı.

In [19]:
# ============================================================
# CELL 3 — 08 NOTEBOOK SONUÇLARINI BUL
# ============================================================

print("=" * 70)
print("CELL 3 — 08 NOTEBOOK SONUÇLARININ KONTROLÜ")
print("=" * 70)

# ------------------------------------------------------------
# Dosyaları uzantılarına göre ayır
# ------------------------------------------------------------

csv_files = sorted(RESULTS_DIR.rglob("*.csv"))
png_files = sorted(RESULTS_DIR.rglob("*.png"))
xlsx_files = sorted(RESULTS_DIR.rglob("*.xlsx"))

print("\nCSV dosyaları:")
print("-" * 70)

if csv_files:
    for f in csv_files:
        print(f.relative_to(RESULTS_DIR))
else:
    print("CSV bulunamadı.")

print("\nPNG dosyaları:")
print("-" * 70)

if png_files:
    for f in png_files:
        print(f.relative_to(RESULTS_DIR))
else:
    print("PNG bulunamadı.")

print("\nXLSX dosyaları:")
print("-" * 70)

if xlsx_files:
    for f in xlsx_files:
        print(f.relative_to(RESULTS_DIR))
else:
    print("XLSX bulunamadı.")


# ------------------------------------------------------------
# Sonuç özeti
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DOSYA ÖZETİ")
print("=" * 70)

print("CSV  :", len(csv_files))
print("PNG  :", len(png_files))
print("XLSX :", len(xlsx_files))

print("\n✅ CELL 3 tamamlandı.")

======================================================================
CELL 3 — 08 NOTEBOOK SONUÇLARININ KONTROLÜ
======================================================================

CSV dosyaları:
----------------------------------------------------------------------
chrd_similarity_results.csv
dataset_summary.csv
improved_similarity.csv
prompt_statistics.csv
prompt_summary.csv
real_image_similarity.csv
similarity_results.csv

PNG dosyaları:
----------------------------------------------------------------------
cultural_value_bar.png
location_bar.png
motif1_bar.png
motif2_bar.png
motif_pairs.png
theme_bar.png
theme_horizontal.png
theme_location_heatmap.png
theme_pie.png
top_locations.png

XLSX dosyaları:
----------------------------------------------------------------------
XLSX bulunamadı.

======================================================================
DOSYA ÖZETİ
======================================================================
CSV  : 7
PNG  : 10
XLSX : 0

✅ CELL 3 tamamlandı.

In [20]:
# ============================================================
# CELL 4 — MEVCUT SONUÇ CSV'LERİNİ KONTROLLÜ OLARAK YÜKLE
# ============================================================

print("=" * 70)
print("CELL 4 — SONUÇ CSV'LERİNİN KONTROLÜ")
print("=" * 70)

# ------------------------------------------------------------
# CSV'leri tekrar bul
# ------------------------------------------------------------

csv_files = sorted(RESULTS_DIR.rglob("*.csv"))

if not csv_files:
    raise FileNotFoundError(
        "\n❌ Results klasöründe CSV bulunamadı.\n"
        f"Kontrol edilen klasör: {RESULTS_DIR}"
    )

# ------------------------------------------------------------
# Her CSV'nin okunabilir olup olmadığını kontrol et
# ------------------------------------------------------------

loaded_csvs = {}
failed_csvs = {}

for csv_path in csv_files:

    relative_name = str(
        csv_path.relative_to(RESULTS_DIR)
    )

    try:

        temp_df = pd.read_csv(
            csv_path,
            encoding="utf-8-sig"
        )

        loaded_csvs[relative_name] = temp_df

        print(
            f"✅ {relative_name}"
            f" | satır: {len(temp_df)}"
            f" | sütun: {len(temp_df.columns)}"
        )

    except Exception as e:

        failed_csvs[relative_name] = str(e)

        print(
            f"⚠️ OKUNAMADI: {relative_name}"
            f"\n   Hata: {e}"
        )


# ------------------------------------------------------------
# Özet
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CSV KONTROL ÖZETİ")
print("=" * 70)

print("Bulunan CSV      :", len(csv_files))
print("Başarıyla okunan :", len(loaded_csvs))
print("Okunamayan       :", len(failed_csvs))


# ------------------------------------------------------------
# Okunan CSV'lerin isimlerini göster
# ------------------------------------------------------------

print("\nKullanılabilir sonuçlar:")

for name in loaded_csvs:
    print(" -", name)


# ------------------------------------------------------------
# Hatalı dosyalar varsa göster
# ------------------------------------------------------------

if failed_csvs:

    print("\n⚠️ Okunamayan dosyalar:")

    for name, error in failed_csvs.items():
        print(f"\n{name}")
        print(error)


print("\n✅ CELL 4 tamamlandı.")

======================================================================
CELL 4 — SONUÇ CSV'LERİNİN KONTROLÜ
======================================================================
✅ chrd_similarity_results.csv | satır: 82 | sütun: 5
✅ dataset_summary.csv | satır: 6 | sütun: 2
✅ improved_similarity.csv | satır: 3 | sütun: 2
✅ prompt_statistics.csv | satır: 3 | sütun: 3
✅ prompt_summary.csv | satır: 1 | sütun: 6
✅ real_image_similarity.csv | satır: 82 | sütun: 5
✅ similarity_results.csv | satır: 3 | sütun: 2

======================================================================
CSV KONTROL ÖZETİ
======================================================================
Bulunan CSV      : 7
Başarıyla okunan : 7
Okunamayan       : 0

Kullanılabilir sonuçlar:
 - chrd_similarity_results.csv
 - dataset_summary.csv
 - improved_similarity.csv
 - prompt_statistics.csv
 - prompt_summary.csv
 - real_image_similarity.csv
 - similarity_results.csv

✅ CELL 4 tamamlandı.

In [21]:
# ============================================================
# CELL 5 — MEVCUT SONUÇLARI SINIFLANDIR
# ============================================================

print("=" * 70)
print("CELL 5 — SONUÇ DOSYALARININ SINIFLANDIRILMASI")
print("=" * 70)

# ------------------------------------------------------------
# Daha önce Cell 4'te oluşturulan loaded_csvs sözlüğünü kullan
# ------------------------------------------------------------

if "loaded_csvs" not in globals():
    raise RuntimeError(
        "❌ loaded_csvs bulunamadı.\n"
        "Önce Cell 4'ü çalıştırmalısın."
    )


# ------------------------------------------------------------
# Dosyaları içeriklerine göre incele
# ------------------------------------------------------------

result_inventory = []

for file_name, df_result in loaded_csvs.items():

    columns = [str(c).lower().strip() for c in df_result.columns]

    result_inventory.append({
        "file": file_name,
        "rows": len(df_result),
        "columns": len(df_result.columns),
        "has_image_id": "image_id" in columns,
        "has_model": "model" in columns,
        "has_language": any(
            c in columns
            for c in ["language", "lang", "prompt_language"]
        ),
        "has_prompt": any(
            "prompt" in c
            for c in columns
        ),
        "has_score": any(
            "score" in c or
            "ccs" in c or
            "tsr" in c or
            "ccgi" in c
            for c in columns
        )
    })


inventory_df = pd.DataFrame(result_inventory)


# ------------------------------------------------------------
# Sonuç envanterini göster
# ------------------------------------------------------------

print("\nSonuç dosyalarının envanteri:\n")

display(inventory_df)


# ------------------------------------------------------------
# Poster analizinde kullanılabilecek dosyaları belirle
# ------------------------------------------------------------

poster_candidates = inventory_df[
    (inventory_df["rows"] > 0)
].copy()


print("\n" + "=" * 70)
print("POSTER ANALİZİ İÇİN ADAY SONUÇLAR")
print("=" * 70)

if len(poster_candidates) == 0:

    print("⚠️ Kullanılabilir sonuç bulunamadı.")

else:

    for file_name in poster_candidates["file"]:
        print("•", file_name)


# ------------------------------------------------------------
# Sonuç
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 5 TAMAMLANDI")
print("=" * 70)

print(
    f"Toplam okunabilir sonuç dosyası : {len(loaded_csvs)}"
)

print(
    f"Poster analizine aday dosya     : {len(poster_candidates)}"
)

print(
    "\n✅ Henüz yeni metrik veya grafik hesaplanmadı."
)

======================================================================
CELL 5 — SONUÇ DOSYALARININ SINIFLANDIRILMASI
======================================================================

Sonuç dosyalarının envanteri:

,file,rows,columns,has_image_id,has_model,has_language,has_prompt,has_score
0,chrd_similarity_results.csv,82,5,False,False,False,False,True
1,dataset_summary.csv,6,2,False,False,False,False,False
2,improved_similarity.csv,3,2,False,False,False,False,False
3,prompt_statistics.csv,3,3,False,False,False,False,False
4,prompt_summary.csv,1,6,False,False,False,True,False
5,real_image_similarity.csv,82,5,False,False,False,False,True
6,similarity_results.csv,3,2,False,False,False,False,False

======================================================================
POSTER ANALİZİ İÇİN ADAY SONUÇLAR
======================================================================
• chrd_similarity_results.csv
• dataset_summary.csv
• improved_similarity.csv
• prompt_statistics.csv
• prompt_summary.csv
• real_image_similarity.csv
• similarity_results.csv

======================================================================
CELL 5 TAMAMLANDI
======================================================================
Toplam okunabilir sonuç dosyası : 7
Poster analizine aday dosya     : 7

✅ Henüz yeni metrik veya grafik hesaplanmadı.

In [22]:
# ============================================================
# CELL 6 — 08 NOTEBOOK SONUÇLARINI ANALİZ İÇİN HAZIRLA
# ============================================================

print("=" * 70)
print("CELL 6 — 08 NOTEBOOK SONUÇLARINI HAZIRLAMA")
print("=" * 70)

# ------------------------------------------------------------
# Cell 4 ve Cell 5 çalışmış olmalı
# ------------------------------------------------------------

if "loaded_csvs" not in globals():
    raise RuntimeError(
        "❌ loaded_csvs bulunamadı. "
        "Önce Cell 4'ü çalıştır."
    )

if "inventory_df" not in globals():
    raise RuntimeError(
        "❌ inventory_df bulunamadı. "
        "Önce Cell 5'i çalıştır."
    )


# ------------------------------------------------------------
# Poster için kullanılabilir CSV'leri seç
# ------------------------------------------------------------

usable_results = {}

for file_name, df_result in loaded_csvs.items():

    # Boş tabloları geç
    if df_result.empty:
        continue

    # Tamamen boş sütunları temizle
    df_clean = df_result.dropna(
        axis=1,
        how="all"
    ).copy()

    # Tamamen boş satırları temizle
    df_clean = df_clean.dropna(
        axis=0,
        how="all"
    ).copy()

    if not df_clean.empty:
        usable_results[file_name] = df_clean


# ------------------------------------------------------------
# Kaç sonuç kaldı?
# ------------------------------------------------------------

print("\nKullanılabilir sonuç sayısı :", len(usable_results))


# ------------------------------------------------------------
# Her sonucu özetle
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("KULLANILABİLİR SONUÇLAR")
print("-" * 70)

for file_name, df_result in usable_results.items():

    print(
        f"\n📄 {file_name}"
    )

    print(
        f"   Satır sayısı : {len(df_result)}"
    )

    print(
        f"   Sütun sayısı : {len(df_result.columns)}"
    )

    print(
        f"   Sütunlar     : {df_result.columns.tolist()}"
    )


# ------------------------------------------------------------
# Sonuçları tek sözlükte tut
# ------------------------------------------------------------

NOTEBOOK_08_RESULTS = usable_results


# ------------------------------------------------------------
# Son kontrol
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 6 TAMAMLANDI")
print("=" * 70)

print(
    "08 notebook sonuçları yeni hesaplama yapılmadan "
    "analiz aşamasına hazırlandı."
)

print(
    "FLUX sonucu bu hücrede kullanılmamaktadır."
)

======================================================================
CELL 6 — 08 NOTEBOOK SONUÇLARINI HAZIRLAMA
======================================================================

Kullanılabilir sonuç sayısı : 7

----------------------------------------------------------------------
KULLANILABİLİR SONUÇLAR
----------------------------------------------------------------------

📄 chrd_similarity_results.csv
   Satır sayısı : 82
   Sütun sayısı : 5
   Sütunlar     : ['file_name', 'theme', 'most_similar_file', 'most_similar_theme', 'similarity_score']

📄 dataset_summary.csv
   Satır sayısı : 6
   Sütun sayısı : 2
   Sütunlar     : ['Statistic', 'Value']

📄 improved_similarity.csv
   Satır sayısı : 3
   Sütun sayısı : 2
   Sütunlar     : ['Metric', 'Similarity']

📄 prompt_statistics.csv
   Satır sayısı : 3
   Sütun sayısı : 3
   Sütunlar     : ['Unnamed: 0', 'Türkçe', 'İngilizce']

📄 prompt_summary.csv
   Satır sayısı : 1
   Sütun sayısı : 6
   Sütunlar     : ['Unnamed: 0', 'Toplam Prompt', 'TR Ortalama Kelime', 'EN Ortalama Kelime', 'Tema Sayısı', 'Motif Sayısı']

📄 real_image_similarity.csv
   Satır sayısı : 82
   Sütun sayısı : 5
   Sütunlar     : ['file_name', 'theme', 'most_similar_file', 'most_similar_theme', 'similarity_score']

📄 similarity_results.csv
   Satır sayısı : 3
   Sütun sayısı : 2
   Sütunlar     : ['Comparison', 'Average Cosine Similarity']

======================================================================
CELL 6 TAMAMLANDI
======================================================================
08 notebook sonuçları yeni hesaplama yapılmadan analiz aşamasına hazırlandı.
FLUX sonucu bu hücrede kullanılmamaktadır.

In [23]:
# ============================================================
# CELL 7 — DATASET ÖZETİ
# ============================================================

print("=" * 70)
print("CELL 7 — CHRD-BENCH DATASET ÖZETİ")
print("=" * 70)

# ------------------------------------------------------------
# 08 sonuçlarının hazır olduğunu kontrol et
# ------------------------------------------------------------

if "NOTEBOOK_08_RESULTS" not in globals():
    raise RuntimeError(
        "❌ NOTEBOOK_08_RESULTS bulunamadı.\n"
        "Önce Cell 6'yı çalıştır."
    )


# ------------------------------------------------------------
# Dataset özeti için uygun tabloyu bulmaya çalış
# ------------------------------------------------------------

summary_candidates = {}

for file_name, df_result in NOTEBOOK_08_RESULTS.items():

    columns = [
        str(c).lower().strip()
        for c in df_result.columns
    ]

    # Dataset/image metadata yapısına benzeyen tabloları aday al
    has_image_id = any(
        c in columns
        for c in ["image_id", "image id"]
    )

    has_theme = any(
        c == "theme"
        for c in columns
    )

    has_location = any(
        c == "location"
        for c in columns
    )

    if has_image_id or has_theme or has_location:
        summary_candidates[file_name] = df_result


# ------------------------------------------------------------
# Adayları göster
# ------------------------------------------------------------

print("\nDataset özeti için bulunan aday tablolar:")

if summary_candidates:

    for file_name, df_result in summary_candidates.items():

        print(
            f"• {file_name}"
            f" | {len(df_result)} satır"
            f" | {len(df_result.columns)} sütun"
        )

else:

    print(
        "⚠️ Dataset özeti için uygun tablo otomatik "
        "olarak belirlenemedi."
    )


# ------------------------------------------------------------
# En uygun tabloyu seç
# ------------------------------------------------------------

DATASET_SUMMARY_DF = None

if summary_candidates:

    # Öncelik: image_id + theme + location içeren tablo
    for file_name, df_result in summary_candidates.items():

        columns = [
            str(c).lower().strip()
            for c in df_result.columns
        ]

        if (
            "image_id" in columns
            and "theme" in columns
            and "location" in columns
        ):

            DATASET_SUMMARY_DF = df_result.copy()

            print(
                "\n✅ Dataset tablosu seçildi:"
            )

            print(file_name)

            break


# ------------------------------------------------------------
# Eğer image_id/theme/location yapısı yoksa
# otomatik seçim yapma
# ------------------------------------------------------------

if DATASET_SUMMARY_DF is None:

    print(
        "\n⚠️ Dataset metadata tablosu bu sonuçlar "
        "arasında bulunamadı."
    )

    print(
        "\nBu aşamada tahmin ederek başka dosya "
        "yüklemiyoruz."
    )

else:

    print("\n" + "-" * 70)
    print("DATASET ÖZETİ")
    print("-" * 70)

    print(
        "Toplam kayıt       :",
        len(DATASET_SUMMARY_DF)
    )

    print(
        "Benzersiz image ID :",
        DATASET_SUMMARY_DF["image_id"].nunique()
    )

    print(
        "Tema sayısı        :",
        DATASET_SUMMARY_DF["theme"].nunique()
    )

    print(
        "Lokasyon sayısı    :",
        DATASET_SUMMARY_DF["location"].nunique()
    )

    print(
        "\nTemalar:"
    )

    print(
        DATASET_SUMMARY_DF["theme"]
        .value_counts(dropna=False)
    )


# ------------------------------------------------------------
# Poster için CSV kaydet
# ------------------------------------------------------------

if DATASET_SUMMARY_DF is not None:

    summary_output = (
        POSTER_OUTPUT_DIR /
        "dataset_summary_final.csv"
    )

    DATASET_SUMMARY_DF.to_csv(
        summary_output,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        "\n✅ Dataset özeti kaydedildi:"
    )

    print(summary_output)


print("\n" + "=" * 70)
print("CELL 7 TAMAMLANDI")
print("=" * 70)

======================================================================
CELL 7 — CHRD-BENCH DATASET ÖZETİ
======================================================================

Dataset özeti için bulunan aday tablolar:
• chrd_similarity_results.csv | 82 satır | 5 sütun
• real_image_similarity.csv | 82 satır | 5 sütun

⚠️ Dataset metadata tablosu bu sonuçlar arasında bulunamadı.

Bu aşamada tahmin ederek başka dosya yüklemiyoruz.

======================================================================
CELL 7 TAMAMLANDI
======================================================================

In [26]:
# ============================================================
# CELL 8 — 08 SONUÇLARINDAN POSTER GRAFİKLERİ
# ============================================================

print("=" * 70)
print("CELL 8 — POSTER GRAFİKLERİ")
print("=" * 70)

# ------------------------------------------------------------
# 1. Ön koşul
# ------------------------------------------------------------

if "NOTEBOOK_08_RESULTS" not in globals():
    raise RuntimeError(
        "❌ NOTEBOOK_08_RESULTS bulunamadı.\n"
        "Önce Cell 6'yı çalıştır."
    )

print(
    "\n08 sonuçlarında bulunan dosya/tablo sayısı:",
    len(NOTEBOOK_08_RESULTS)
)


# ------------------------------------------------------------
# 2. Sonuçları göster
# ------------------------------------------------------------

print("\n08 SONUÇLARI:")

for name, obj in NOTEBOOK_08_RESULTS.items():

    if isinstance(obj, pd.DataFrame):

        print(
            f"• {name}"
            f" | satır={len(obj)}"
            f" | sütun={len(obj.columns)}"
        )

    else:

        print(
            f"• {name}"
            f" | tür={type(obj).__name__}"
        )


# ------------------------------------------------------------
# 3. Poster grafik klasörü
# ------------------------------------------------------------

FIGURES_DIR = POSTER_OUTPUT_DIR / "figures"

FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 4. Grafik olabilecek tabloları bul
# ------------------------------------------------------------

POSSIBLE_TABLES = {}

for name, obj in NOTEBOOK_08_RESULTS.items():

    if not isinstance(obj, pd.DataFrame):
        continue

    if obj.empty:
        continue

    columns = [
        str(c).strip().lower()
        for c in obj.columns
    ]

    # Frekans / dağılım tabloları
    frequency_words = [
        "count",
        "frequency",
        "freq",
        "n",
        "value"
    ]

    category_words = [
        "theme",
        "location",
        "motif",
        "category",
        "language",
        "model",
        "prompt"
    ]

    has_category = any(
        any(word in col for word in category_words)
        for col in columns
    )

    has_frequency = any(
        any(word == col or word in col for word in frequency_words)
        for col in columns
    )

    if has_category or has_frequency:

        POSSIBLE_TABLES[name] = obj


print(
    "\nGrafik üretimine uygun bulunan tablolar:",
    len(POSSIBLE_TABLES)
)

for name, df_result in POSSIBLE_TABLES.items():

    print(
        f"• {name}"
        f" → {df_result.columns.tolist()}"
    )


# ------------------------------------------------------------
# 5. Şimdilik otomatik grafik üretme
# ------------------------------------------------------------

print("\n" + "-" * 70)

if not POSSIBLE_TABLES:

    print(
        "⚠️ 08 sonuçları içerisinde poster için "
        "otomatik seçilebilecek dataset grafik tablosu bulunamadı."
    )

    print(
        "\nBu bir veri kaybı anlamına gelmez."
    )

    print(
        "08 notebook sonuçları korunuyor."
    )

    print(
        "Bir sonraki aşamada doğrudan 08'in "
        "mevcut grafik/CSV çıktılarından devam edeceğiz."
    )

else:

    print(
        "✅ 08 notebook sonuçları bulundu."
    )

    print(
        "Grafikleri rastgele yeniden üretmiyoruz."
    )

    print(
        "Poster için gerekli olan mevcut sonuçları "
        "kullanacağız."
    )


# ------------------------------------------------------------
# 6. Poster klasörünün içeriğini göster
# ------------------------------------------------------------

print("\nPoster çıktı klasörü:")

print(
    POSTER_OUTPUT_DIR
)

print("\nMevcut poster dosyaları:")

for path in sorted(
    POSTER_OUTPUT_DIR.rglob("*")
):

    if path.is_file():

        print(
            "•",
            path.relative_to(POSTER_OUTPUT_DIR)
        )


print("\n" + "=" * 70)
print("CELL 8 TAMAMLANDI")
print("=" * 70)

======================================================================
CELL 8 — POSTER GRAFİKLERİ
======================================================================

08 sonuçlarında bulunan dosya/tablo sayısı: 7

08 SONUÇLARI:
• chrd_similarity_results.csv | satır=82 | sütun=5
• dataset_summary.csv | satır=6 | sütun=2
• improved_similarity.csv | satır=3 | sütun=2
• prompt_statistics.csv | satır=3 | sütun=3
• prompt_summary.csv | satır=1 | sütun=6
• real_image_similarity.csv | satır=82 | sütun=5
• similarity_results.csv | satır=3 | sütun=2

Grafik üretimine uygun bulunan tablolar: 6
• chrd_similarity_results.csv → ['file_name', 'theme', 'most_similar_file', 'most_similar_theme', 'similarity_score']
• dataset_summary.csv → ['Statistic', 'Value']
• prompt_statistics.csv → ['Unnamed: 0', 'Türkçe', 'İngilizce']
• prompt_summary.csv → ['Unnamed: 0', 'Toplam Prompt', 'TR Ortalama Kelime', 'EN Ortalama Kelime', 'Tema Sayısı', 'Motif Sayısı']
• real_image_similarity.csv → ['file_name', 'theme', 'most_similar_file', 'most_similar_theme', 'similarity_score']
• similarity_results.csv → ['Comparison', 'Average Cosine Similarity']

----------------------------------------------------------------------
✅ 08 notebook sonuçları bulundu.
Grafikleri rastgele yeniden üretmiyoruz.
Poster için gerekli olan mevcut sonuçları kullanacağız.

Poster çıktı klasörü:
C:\CHRD_Project\results\poster_final

Mevcut poster dosyaları:

======================================================================
CELL 8 TAMAMLANDI
======================================================================

In [27]:
# ============================================================
# CELL 9 — 08 SONUÇLARININ POSTER ENVANTERİ
# ============================================================

print("=" * 70)
print("CELL 9 — POSTER İÇİN 08 SONUÇ ENVANTERİ")
print("=" * 70)

# ------------------------------------------------------------
# 1. 08 sonuçlarının kontrolü
# ------------------------------------------------------------

if "NOTEBOOK_08_RESULTS" not in globals():
    raise RuntimeError(
        "❌ NOTEBOOK_08_RESULTS bulunamadı.\n"
        "Önce Cell 6'yı çalıştır."
    )


# ------------------------------------------------------------
# 2. Poster çıktı klasörleri
# ------------------------------------------------------------

POSTER_CSV_DIR = POSTER_OUTPUT_DIR / "csv"
POSTER_FIGURES_DIR = POSTER_OUTPUT_DIR / "figures"

POSTER_CSV_DIR.mkdir(
    parents=True,
    exist_ok=True
)

POSTER_FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 3. 08 sonuçlarını sınıflandır
# ------------------------------------------------------------

inventory = []

for name, obj in NOTEBOOK_08_RESULTS.items():

    # -------------------------
    # DataFrame
    # -------------------------

    if isinstance(obj, pd.DataFrame):

        inventory.append({
            "name": name,
            "type": "DataFrame",
            "rows": len(obj),
            "columns": len(obj.columns),
            "columns_list": ", ".join(
                map(str, obj.columns.tolist())
            )
        })

    # -------------------------
    # Dosya / Path
    # -------------------------

    elif isinstance(
        obj,
        (str, Path)
    ):

        path = Path(obj)

        inventory.append({
            "name": name,
            "type": "File",
            "rows": "",
            "columns": "",
            "columns_list": str(path)
        })

    # -------------------------
    # Diğer
    # -------------------------

    else:

        inventory.append({
            "name": name,
            "type": type(obj).__name__,
            "rows": "",
            "columns": "",
            "columns_list": ""
        })


# ------------------------------------------------------------
# 4. Envanter DataFrame
# ------------------------------------------------------------

POSTER_08_INVENTORY = pd.DataFrame(
    inventory
)


# ------------------------------------------------------------
# 5. CSV olarak kaydet
# ------------------------------------------------------------

inventory_path = (
    POSTER_CSV_DIR /
    "notebook08_results_inventory.csv"
)

POSTER_08_INVENTORY.to_csv(
    inventory_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 6. Ekrana göster
# ------------------------------------------------------------

print(
    "\n08 notebook sonuç envanteri:"
)

display(
    POSTER_08_INVENTORY
)


# ------------------------------------------------------------
# 7. Özet
# ------------------------------------------------------------

print("\n" + "-" * 70)

print(
    "Toplam 08 sonucu:",
    len(POSTER_08_INVENTORY)
)

print(
    "DataFrame sonucu:",
    (
        POSTER_08_INVENTORY["type"]
        == "DataFrame"
    ).sum()
)

print(
    "Dosya sonucu:",
    (
        POSTER_08_INVENTORY["type"]
        == "File"
    ).sum()
)

print(
    "\nEnvanter kaydedildi:"
)

print(
    inventory_path
)


print("\n" + "=" * 70)
print("✅ CELL 9 TAMAMLANDI")
print("=" * 70)

======================================================================
CELL 9 — POSTER İÇİN 08 SONUÇ ENVANTERİ
======================================================================

08 notebook sonuç envanteri:

,name,type,rows,columns,columns_list
0,chrd_similarity_results.csv,DataFrame,82,5,"file_name, theme, most_similar_file, most_simi..."
1,dataset_summary.csv,DataFrame,6,2,"Statistic, Value"
2,improved_similarity.csv,DataFrame,3,2,"Metric, Similarity"
3,prompt_statistics.csv,DataFrame,3,3,"Unnamed: 0, Türkçe, İngilizce"
4,prompt_summary.csv,DataFrame,1,6,"Unnamed: 0, Toplam Prompt, TR Ortalama Kelime,..."
5,real_image_similarity.csv,DataFrame,82,5,"file_name, theme, most_similar_file, most_simi..."
6,similarity_results.csv,DataFrame,3,2,"Comparison, Average Cosine Similarity"

----------------------------------------------------------------------
Toplam 08 sonucu: 7
DataFrame sonucu: 7
Dosya sonucu: 0

Envanter kaydedildi:
C:\CHRD_Project\results\poster_final\csv\notebook08_results_inventory.csv

======================================================================
✅ CELL 9 TAMAMLANDI
======================================================================